// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/gateway/tasks/services.proto

package gateway_tasks

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	TaskToCreate  *CreateTaskRequest_TaskPrototype `protobuf:"bytes,1,opt,name=task_to_create,json=taskToCreate,proto3" json:"task_to_create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskRequest) GetTaskToCreate() *CreateTaskRequest_TaskPrototype {
	if x != nil {
		return x.TaskToCreate
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Id            int64                            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskToUpdate  *UpdateTaskRequest_TaskPrototype `protobuf:"bytes,2,opt,name=task_to_update,json=taskToUpdate,proto3" json:"task_to_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskRequest) GetTaskToUpdate() *UpdateTaskRequest_TaskPrototype {
	if x != nil {
		return x.TaskToUpdate
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{5}
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{7}
}

type GetAllTaskDependenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTaskDependenciesRequest) Reset() {
	*x = GetAllTaskDependenciesRequest{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTaskDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTaskDependenciesRequest) ProtoMessage() {}

func (x *GetAllTaskDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTaskDependenciesRequest.ProtoReflect.Descriptor instead.
func (*GetAllTaskDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllTaskDependenciesRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllTaskDependenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTaskDependenciesResponse) Reset() {
	*x = GetAllTaskDependenciesResponse{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTaskDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTaskDependenciesResponse) ProtoMessage() {}

func (x *GetAllTaskDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTaskDependenciesResponse.ProtoReflect.Descriptor instead.
func (*GetAllTaskDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllTaskDependenciesResponse) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CreateTaskRequest_TaskPrototype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Deps          []int64                `protobuf:"varint,3,rep,packed,name=deps,proto3" json:"deps,omitempty"`
	Priority      Priority               `protobuf:"varint,4,opt,name=priority,proto3,enum=api.v1.gateway.tasks.Priority" json:"priority,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FinishTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest_TaskPrototype) Reset() {
	*x = CreateTaskRequest_TaskPrototype{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest_TaskPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest_TaskPrototype) ProtoMessage() {}

func (x *CreateTaskRequest_TaskPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest_TaskPrototype.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest_TaskPrototype) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateTaskRequest_TaskPrototype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest_TaskPrototype) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest_TaskPrototype) GetDeps() []int64 {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *CreateTaskRequest_TaskPrototype) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *CreateTaskRequest_TaskPrototype) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateTaskRequest_TaskPrototype) GetFinishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishTime
	}
	return nil
}

type UpdateTaskRequest_TaskPrototype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Deps          []int64                `protobuf:"varint,3,rep,packed,name=deps,proto3" json:"deps,omitempty"`
	Priority      *Priority              `protobuf:"varint,4,opt,name=priority,proto3,enum=api.v1.gateway.tasks.Priority,oneof" json:"priority,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	FinishTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finish_time,json=finishTime,proto3,oneof" json:"finish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest_TaskPrototype) Reset() {
	*x = UpdateTaskRequest_TaskPrototype{}
	mi := &file_api_gateway_tasks_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest_TaskPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest_TaskPrototype) ProtoMessage() {}

func (x *UpdateTaskRequest_TaskPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_tasks_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest_TaskPrototype.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest_TaskPrototype) Descriptor() ([]byte, []int) {
	return file_api_gateway_tasks_services_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateTaskRequest_TaskPrototype) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTaskRequest_TaskPrototype) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTaskRequest_TaskPrototype) GetDeps() []int64 {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *UpdateTaskRequest_TaskPrototype) GetPriority() Priority {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *UpdateTaskRequest_TaskPrototype) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateTaskRequest_TaskPrototype) GetFinishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishTime
	}
	return nil
}

var File_api_gateway_tasks_services_proto protoreflect.FileDescriptor

const file_api_gateway_tasks_services_proto_rawDesc = "" +
	"\n" +
	" api/gateway/tasks/services.proto\x12\x14api.v1.gateway.tasks\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1eapi/gateway/tasks/models.proto\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x0fGetTaskResponse\x12.\n" +
	"\x04task\x18\x01 \x01(\v2\x1a.api.v1.gateway.tasks.TaskR\x04task\"\x80\x03\n" +
	"\x11CreateTaskRequest\x12[\n" +
	"\x0etask_to_create\x18\x01 \x01(\v25.api.v1.gateway.tasks.CreateTaskRequest.TaskPrototypeR\ftaskToCreate\x1a\x8d\x02\n" +
	"\rTaskPrototype\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04deps\x18\x03 \x03(\x03R\x04deps\x12:\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x1e.api.v1.gateway.tasks.PriorityR\bpriority\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12;\n" +
	"\vfinish_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishTime\"$\n" +
	"\x12CreateTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xee\x03\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12[\n" +
	"\x0etask_to_update\x18\x02 \x01(\v25.api.v1.gateway.tasks.UpdateTaskRequest.TaskPrototypeR\ftaskToUpdate\x1a\xeb\x02\n" +
	"\rTaskPrototype\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x12\n" +
	"\x04deps\x18\x03 \x03(\x03R\x04deps\x12?\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x1e.api.v1.gateway.tasks.PriorityH\x02R\bpriority\x88\x01\x01\x12>\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tstartTime\x88\x01\x01\x12@\n" +
	"\vfinish_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\n" +
	"finishTime\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_priorityB\r\n" +
	"\v_start_timeB\x0e\n" +
	"\f_finish_time\"\x14\n" +
	"\x12UpdateTaskResponse\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteTaskResponse\"/\n" +
	"\x1dGetAllTaskDependenciesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"2\n" +
	"\x1eGetAllTaskDependenciesResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids2\xb6\x05\n" +
	"\vTaskService\x12t\n" +
	"\aGetTask\x12$.api.v1.gateway.tasks.GetTaskRequest\x1a%.api.v1.gateway.tasks.GetTaskResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/tasks/{id=*}\x12y\n" +
	"\n" +
	"CreateTask\x12'.api.v1.gateway.tasks.CreateTaskRequest\x1a(.api.v1.gateway.tasks.CreateTaskResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/tasks\x12\x8d\x01\n" +
	"\n" +
	"UpdateTask\x12'.api.v1.gateway.tasks.UpdateTaskRequest\x1a(.api.v1.gateway.tasks.UpdateTaskResponse\",\x82\xd3\xe4\x93\x02&:\x0etask_to_update2\x14/api/v1/tasks/{id=*}\x12}\n" +
	"\n" +
	"DeleteTask\x12'.api.v1.gateway.tasks.DeleteTaskRequest\x1a(.api.v1.gateway.tasks.DeleteTaskResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/v1/tasks/{id=*}\x12\xa6\x01\n" +
	"\x16GetAllTaskDependencies\x123.api.v1.gateway.tasks.GetAllTaskDependenciesRequest\x1a4.api.v1.gateway.tasks.GetAllTaskDependenciesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/tasks/{id=*}/depsBOZMgithub.com/bogi-lyceya-44/gateway/internal/pb/api/gateway/tasks;gateway_tasksb\x06proto3"

var (
	file_api_gateway_tasks_services_proto_rawDescOnce sync.Once
	file_api_gateway_tasks_services_proto_rawDescData []byte
)

func file_api_gateway_tasks_services_proto_rawDescGZIP() []byte {
	file_api_gateway_tasks_services_proto_rawDescOnce.Do(func() {
		file_api_gateway_tasks_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_tasks_services_proto_rawDesc), len(file_api_gateway_tasks_services_proto_rawDesc)))
	})
	return file_api_gateway_tasks_services_proto_rawDescData
}

var file_api_gateway_tasks_services_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_gateway_tasks_services_proto_goTypes = []any{
	(*GetTaskRequest)(nil),                  // 0: api.v1.gateway.tasks.GetTaskRequest
	(*GetTaskResponse)(nil),                 // 1: api.v1.gateway.tasks.GetTaskResponse
	(*CreateTaskRequest)(nil),               // 2: api.v1.gateway.tasks.CreateTaskRequest
	(*CreateTaskResponse)(nil),              // 3: api.v1.gateway.tasks.CreateTaskResponse
	(*UpdateTaskRequest)(nil),               // 4: api.v1.gateway.tasks.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),              // 5: api.v1.gateway.tasks.UpdateTaskResponse
	(*DeleteTaskRequest)(nil),               // 6: api.v1.gateway.tasks.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),              // 7: api.v1.gateway.tasks.DeleteTaskResponse
	(*GetAllTaskDependenciesRequest)(nil),   // 8: api.v1.gateway.tasks.GetAllTaskDependenciesRequest
	(*GetAllTaskDependenciesResponse)(nil),  // 9: api.v1.gateway.tasks.GetAllTaskDependenciesResponse
	(*CreateTaskRequest_TaskPrototype)(nil), // 10: api.v1.gateway.tasks.CreateTaskRequest.TaskPrototype
	(*UpdateTaskRequest_TaskPrototype)(nil), // 11: api.v1.gateway.tasks.UpdateTaskRequest.TaskPrototype
	(*Task)(nil),                            // 12: api.v1.gateway.tasks.Task
	(Priority)(0),                           // 13: api.v1.gateway.tasks.Priority
	(*timestamppb.Timestamp)(nil),           // 14: google.protobuf.Timestamp
}
var file_api_gateway_tasks_services_proto_depIdxs = []int32{
	12, // 0: api.v1.gateway.tasks.GetTaskResponse.task:type_name -> api.v1.gateway.tasks.Task
	10, // 1: api.v1.gateway.tasks.CreateTaskRequest.task_to_create:type_name -> api.v1.gateway.tasks.CreateTaskRequest.TaskPrototype
	11, // 2: api.v1.gateway.tasks.UpdateTaskRequest.task_to_update:type_name -> api.v1.gateway.tasks.UpdateTaskRequest.TaskPrototype
	13, // 3: api.v1.gateway.tasks.CreateTaskRequest.TaskPrototype.priority:type_name -> api.v1.gateway.tasks.Priority
	14, // 4: api.v1.gateway.tasks.CreateTaskRequest.TaskPrototype.start_time:type_name -> google.protobuf.Timestamp
	14, // 5: api.v1.gateway.tasks.CreateTaskRequest.TaskPrototype.finish_time:type_name -> google.protobuf.Timestamp
	13, // 6: api.v1.gateway.tasks.UpdateTaskRequest.TaskPrototype.priority:type_name -> api.v1.gateway.tasks.Priority
	14, // 7: api.v1.gateway.tasks.UpdateTaskRequest.TaskPrototype.start_time:type_name -> google.protobuf.Timestamp
	14, // 8: api.v1.gateway.tasks.UpdateTaskRequest.TaskPrototype.finish_time:type_name -> google.protobuf.Timestamp
	0,  // 9: api.v1.gateway.tasks.TaskService.GetTask:input_type -> api.v1.gateway.tasks.GetTaskRequest
	2,  // 10: api.v1.gateway.tasks.TaskService.CreateTask:input_type -> api.v1.gateway.tasks.CreateTaskRequest
	4,  // 11: api.v1.gateway.tasks.TaskService.UpdateTask:input_type -> api.v1.gateway.tasks.UpdateTaskRequest
	6,  // 12: api.v1.gateway.tasks.TaskService.DeleteTask:input_type -> api.v1.gateway.tasks.DeleteTaskRequest
	8,  // 13: api.v1.gateway.tasks.TaskService.GetAllTaskDependencies:input_type -> api.v1.gateway.tasks.GetAllTaskDependenciesRequest
	1,  // 14: api.v1.gateway.tasks.TaskService.GetTask:output_type -> api.v1.gateway.tasks.GetTaskResponse
	3,  // 15: api.v1.gateway.tasks.TaskService.CreateTask:output_type -> api.v1.gateway.tasks.CreateTaskResponse
	5,  // 16: api.v1.gateway.tasks.TaskService.UpdateTask:output_type -> api.v1.gateway.tasks.UpdateTaskResponse
	7,  // 17: api.v1.gateway.tasks.TaskService.DeleteTask:output_type -> api.v1.gateway.tasks.DeleteTaskResponse
	9,  // 18: api.v1.gateway.tasks.TaskService.GetAllTaskDependencies:output_type -> api.v1.gateway.tasks.GetAllTaskDependenciesResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_gateway_tasks_services_proto_init() }
func file_api_gateway_tasks_services_proto_init() {
	if File_api_gateway_tasks_services_proto != nil {
		return
	}
	file_api_gateway_tasks_models_proto_init()
	file_api_gateway_tasks_services_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_tasks_services_proto_rawDesc), len(file_api_gateway_tasks_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_tasks_services_proto_goTypes,
		DependencyIndexes: file_api_gateway_tasks_services_proto_depIdxs,
		MessageInfos:      file_api_gateway_tasks_services_proto_msgTypes,
	}.Build()
	File_api_gateway_tasks_services_proto = out.File
	file_api_gateway_tasks_services_proto_goTypes = nil
	file_api_gateway_tasks_services_proto_depIdxs = nil
}
