// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/gateway/topics/services.proto

package gateway_topics

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicRequest) Reset() {
	*x = GetTopicRequest{}
	mi := &file_api_gateway_topics_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicRequest) ProtoMessage() {}

func (x *GetTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_topics_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicRequest.ProtoReflect.Descriptor instead.
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_topics_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopicRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *Topic                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicResponse) Reset() {
	*x = GetTopicResponse{}
	mi := &file_api_gateway_topics_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicResponse) ProtoMessage() {}

func (x *GetTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_topics_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicResponse.ProtoReflect.Descriptor instead.
func (*GetTopicResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_topics_services_proto_rawDescGZIP(), []int{1}
}

func (x *GetTopicResponse) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	TopicToCreate *CreateTopicRequest_TopicPrototype `protobuf:"bytes,1,opt,name=topic_to_create,json=topicToCreate,proto3" json:"topic_to_create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_api_gateway_topics_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_topics_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_topics_services_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTopicRequest) GetTopicToCreate() *CreateTopicRequest_TopicPrototype {
	if x != nil {
		return x.TopicToCreate
	}
	return nil
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_api_gateway_topics_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_topics_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_topics_services_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTopicResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateTopicRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Id            int64                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TopicToUpdate *UpdateTopicRequest_TopicPrototype `protobuf:"bytes,2,opt,name=topic_to_update,json=topicToUpdate,proto3" json:"topic_to_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicRequest) Reset() {
	*x = UpdateTopicRequest{}
	mi := &file_api_gateway_topics_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicRequest) ProtoMessage() {}

func (x *UpdateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_topics_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicRequest.ProtoReflect.Descriptor instead.
func (*UpdateTopicRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_topics_services_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTopicRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTopicRequest) GetTopicToUpdate() *UpdateTopicRequest_TopicPrototype {
	if x != nil {
		return x.TopicToUpdate
	}
	return nil
}

type UpdateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicResponse) Reset() {
	*x = UpdateTopicResponse{}
	mi := &file_api_gateway_topics_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicResponse) ProtoMessage() {}

func (x *UpdateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_topics_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicResponse.ProtoReflect.Descriptor instead.
func (*UpdateTopicResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_topics_services_proto_rawDescGZIP(), []int{5}
}

type DeleteTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicRequest) Reset() {
	*x = DeleteTopicRequest{}
	mi := &file_api_gateway_topics_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicRequest) ProtoMessage() {}

func (x *DeleteTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_topics_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicRequest.ProtoReflect.Descriptor instead.
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_topics_services_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTopicRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicResponse) Reset() {
	*x = DeleteTopicResponse{}
	mi := &file_api_gateway_topics_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicResponse) ProtoMessage() {}

func (x *DeleteTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_topics_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicResponse.ProtoReflect.Descriptor instead.
func (*DeleteTopicResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_topics_services_proto_rawDescGZIP(), []int{7}
}

type CreateTopicRequest_TopicPrototype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TaskIds       []int64                `protobuf:"varint,2,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest_TopicPrototype) Reset() {
	*x = CreateTopicRequest_TopicPrototype{}
	mi := &file_api_gateway_topics_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest_TopicPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest_TopicPrototype) ProtoMessage() {}

func (x *CreateTopicRequest_TopicPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_topics_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest_TopicPrototype.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest_TopicPrototype) Descriptor() ([]byte, []int) {
	return file_api_gateway_topics_services_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateTopicRequest_TopicPrototype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTopicRequest_TopicPrototype) GetTaskIds() []int64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type UpdateTopicRequest_TopicPrototype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	TaskIds       []int64                `protobuf:"varint,2,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicRequest_TopicPrototype) Reset() {
	*x = UpdateTopicRequest_TopicPrototype{}
	mi := &file_api_gateway_topics_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicRequest_TopicPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicRequest_TopicPrototype) ProtoMessage() {}

func (x *UpdateTopicRequest_TopicPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_topics_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicRequest_TopicPrototype.ProtoReflect.Descriptor instead.
func (*UpdateTopicRequest_TopicPrototype) Descriptor() ([]byte, []int) {
	return file_api_gateway_topics_services_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateTopicRequest_TopicPrototype) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTopicRequest_TopicPrototype) GetTaskIds() []int64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

var File_api_gateway_topics_services_proto protoreflect.FileDescriptor

const file_api_gateway_topics_services_proto_rawDesc = "" +
	"\n" +
	"!api/gateway/topics/services.proto\x12\x15api.v1.gateway.topics\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fapi/gateway/topics/models.proto\"!\n" +
	"\x0fGetTopicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x10GetTopicResponse\x122\n" +
	"\x05topic\x18\x01 \x01(\v2\x1c.api.v1.gateway.topics.TopicR\x05topic\"\xb7\x01\n" +
	"\x12CreateTopicRequest\x12`\n" +
	"\x0ftopic_to_create\x18\x01 \x01(\v28.api.v1.gateway.topics.CreateTopicRequest.TopicPrototypeR\rtopicToCreate\x1a?\n" +
	"\x0eTopicPrototype\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\x03R\ataskIds\"%\n" +
	"\x13CreateTopicResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd5\x01\n" +
	"\x12UpdateTopicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12`\n" +
	"\x0ftopic_to_update\x18\x02 \x01(\v28.api.v1.gateway.topics.UpdateTopicRequest.TopicPrototypeR\rtopicToUpdate\x1aM\n" +
	"\x0eTopicPrototype\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\x03R\ataskIdsB\a\n" +
	"\x05_name\"\x15\n" +
	"\x13UpdateTopicResponse\"$\n" +
	"\x12DeleteTopicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13DeleteTopicResponse2\xa8\x04\n" +
	"\fTopicService\x12z\n" +
	"\bGetTopic\x12&.api.v1.gateway.topics.GetTopicRequest\x1a'.api.v1.gateway.topics.GetTopicResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/topics/{id=*}\x12\x7f\n" +
	"\vCreateTopic\x12).api.v1.gateway.topics.CreateTopicRequest\x1a*.api.v1.gateway.topics.CreateTopicResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/api/v1/topics\x12\x94\x01\n" +
	"\vUpdateTopic\x12).api.v1.gateway.topics.UpdateTopicRequest\x1a*.api.v1.gateway.topics.UpdateTopicResponse\".\x82\xd3\xe4\x93\x02(:\x0ftopic_to_update\x1a\x15/api/v1/topics/{id=*}\x12\x83\x01\n" +
	"\vDeleteTopic\x12).api.v1.gateway.topics.DeleteTopicRequest\x1a*.api.v1.gateway.topics.DeleteTopicResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/topics/{id=*}BQZOgithub.com/bogi-lyceya-44/gateway/internal/pb/api/gateway/topics;gateway_topicsb\x06proto3"

var (
	file_api_gateway_topics_services_proto_rawDescOnce sync.Once
	file_api_gateway_topics_services_proto_rawDescData []byte
)

func file_api_gateway_topics_services_proto_rawDescGZIP() []byte {
	file_api_gateway_topics_services_proto_rawDescOnce.Do(func() {
		file_api_gateway_topics_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_topics_services_proto_rawDesc), len(file_api_gateway_topics_services_proto_rawDesc)))
	})
	return file_api_gateway_topics_services_proto_rawDescData
}

var file_api_gateway_topics_services_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_gateway_topics_services_proto_goTypes = []any{
	(*GetTopicRequest)(nil),                   // 0: api.v1.gateway.topics.GetTopicRequest
	(*GetTopicResponse)(nil),                  // 1: api.v1.gateway.topics.GetTopicResponse
	(*CreateTopicRequest)(nil),                // 2: api.v1.gateway.topics.CreateTopicRequest
	(*CreateTopicResponse)(nil),               // 3: api.v1.gateway.topics.CreateTopicResponse
	(*UpdateTopicRequest)(nil),                // 4: api.v1.gateway.topics.UpdateTopicRequest
	(*UpdateTopicResponse)(nil),               // 5: api.v1.gateway.topics.UpdateTopicResponse
	(*DeleteTopicRequest)(nil),                // 6: api.v1.gateway.topics.DeleteTopicRequest
	(*DeleteTopicResponse)(nil),               // 7: api.v1.gateway.topics.DeleteTopicResponse
	(*CreateTopicRequest_TopicPrototype)(nil), // 8: api.v1.gateway.topics.CreateTopicRequest.TopicPrototype
	(*UpdateTopicRequest_TopicPrototype)(nil), // 9: api.v1.gateway.topics.UpdateTopicRequest.TopicPrototype
	(*Topic)(nil),                             // 10: api.v1.gateway.topics.Topic
}
var file_api_gateway_topics_services_proto_depIdxs = []int32{
	10, // 0: api.v1.gateway.topics.GetTopicResponse.topic:type_name -> api.v1.gateway.topics.Topic
	8,  // 1: api.v1.gateway.topics.CreateTopicRequest.topic_to_create:type_name -> api.v1.gateway.topics.CreateTopicRequest.TopicPrototype
	9,  // 2: api.v1.gateway.topics.UpdateTopicRequest.topic_to_update:type_name -> api.v1.gateway.topics.UpdateTopicRequest.TopicPrototype
	0,  // 3: api.v1.gateway.topics.TopicService.GetTopic:input_type -> api.v1.gateway.topics.GetTopicRequest
	2,  // 4: api.v1.gateway.topics.TopicService.CreateTopic:input_type -> api.v1.gateway.topics.CreateTopicRequest
	4,  // 5: api.v1.gateway.topics.TopicService.UpdateTopic:input_type -> api.v1.gateway.topics.UpdateTopicRequest
	6,  // 6: api.v1.gateway.topics.TopicService.DeleteTopic:input_type -> api.v1.gateway.topics.DeleteTopicRequest
	1,  // 7: api.v1.gateway.topics.TopicService.GetTopic:output_type -> api.v1.gateway.topics.GetTopicResponse
	3,  // 8: api.v1.gateway.topics.TopicService.CreateTopic:output_type -> api.v1.gateway.topics.CreateTopicResponse
	5,  // 9: api.v1.gateway.topics.TopicService.UpdateTopic:output_type -> api.v1.gateway.topics.UpdateTopicResponse
	7,  // 10: api.v1.gateway.topics.TopicService.DeleteTopic:output_type -> api.v1.gateway.topics.DeleteTopicResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_gateway_topics_services_proto_init() }
func file_api_gateway_topics_services_proto_init() {
	if File_api_gateway_topics_services_proto != nil {
		return
	}
	file_api_gateway_topics_models_proto_init()
	file_api_gateway_topics_services_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_topics_services_proto_rawDesc), len(file_api_gateway_topics_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_topics_services_proto_goTypes,
		DependencyIndexes: file_api_gateway_topics_services_proto_depIdxs,
		MessageInfos:      file_api_gateway_topics_services_proto_msgTypes,
	}.Build()
	File_api_gateway_topics_services_proto = out.File
	file_api_gateway_topics_services_proto_goTypes = nil
	file_api_gateway_topics_services_proto_depIdxs = nil
}
