// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/gateway/boards/services.proto

package gateway_boards

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/bogi-lyceya-44/gateway/internal/pb/api/gateway/tasks"
	topics "github.com/bogi-lyceya-44/gateway/internal/pb/api/gateway/topics"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardRequest) Reset() {
	*x = GetBoardRequest{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardRequest) ProtoMessage() {}

func (x *GetBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardRequest.ProtoReflect.Descriptor instead.
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetBoardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardResponse) Reset() {
	*x = GetBoardResponse{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardResponse) ProtoMessage() {}

func (x *GetBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardResponse.ProtoReflect.Descriptor instead.
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{1}
}

func (x *GetBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type CreateBoardRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	BoardToCreate *CreateBoardRequest_BoardPrototype `protobuf:"bytes,1,opt,name=board_to_create,json=boardToCreate,proto3" json:"board_to_create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBoardRequest) GetBoardToCreate() *CreateBoardRequest_BoardPrototype {
	if x != nil {
		return x.BoardToCreate
	}
	return nil
}

type CreateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardResponse) Reset() {
	*x = CreateBoardResponse{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardResponse) ProtoMessage() {}

func (x *CreateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardResponse.ProtoReflect.Descriptor instead.
func (*CreateBoardResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBoardResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateBoardRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Id            int64                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BoardToUpdate *UpdateBoardRequest_BoardPrototype `protobuf:"bytes,2,opt,name=board_to_update,json=boardToUpdate,proto3" json:"board_to_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardRequest) Reset() {
	*x = UpdateBoardRequest{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardRequest) ProtoMessage() {}

func (x *UpdateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBoardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBoardRequest) GetBoardToUpdate() *UpdateBoardRequest_BoardPrototype {
	if x != nil {
		return x.BoardToUpdate
	}
	return nil
}

type UpdateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardResponse) Reset() {
	*x = UpdateBoardResponse{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardResponse) ProtoMessage() {}

func (x *UpdateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardResponse.ProtoReflect.Descriptor instead.
func (*UpdateBoardResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{5}
}

type DeleteBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardRequest) Reset() {
	*x = DeleteBoardRequest{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardRequest) ProtoMessage() {}

func (x *DeleteBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardRequest.ProtoReflect.Descriptor instead.
func (*DeleteBoardRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBoardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardResponse) Reset() {
	*x = DeleteBoardResponse{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardResponse) ProtoMessage() {}

func (x *DeleteBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardResponse.ProtoReflect.Descriptor instead.
func (*DeleteBoardResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{7}
}

type GetBoardContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardContentRequest) Reset() {
	*x = GetBoardContentRequest{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardContentRequest) ProtoMessage() {}

func (x *GetBoardContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardContentRequest.ProtoReflect.Descriptor instead.
func (*GetBoardContentRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{8}
}

func (x *GetBoardContentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBoardContentResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Topics        []*topics.TopicWithFetchedTasks `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardContentResponse) Reset() {
	*x = GetBoardContentResponse{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardContentResponse) ProtoMessage() {}

func (x *GetBoardContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardContentResponse.ProtoReflect.Descriptor instead.
func (*GetBoardContentResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{9}
}

func (x *GetBoardContentResponse) GetTopics() []*topics.TopicWithFetchedTasks {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetAllBoardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBoardsRequest) Reset() {
	*x = GetAllBoardsRequest{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBoardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBoardsRequest) ProtoMessage() {}

func (x *GetAllBoardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBoardsRequest.ProtoReflect.Descriptor instead.
func (*GetAllBoardsRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{10}
}

type GetAllBoardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boards        []*Board               `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBoardsResponse) Reset() {
	*x = GetAllBoardsResponse{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBoardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBoardsResponse) ProtoMessage() {}

func (x *GetAllBoardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBoardsResponse.ProtoReflect.Descriptor instead.
func (*GetAllBoardsResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllBoardsResponse) GetBoards() []*Board {
	if x != nil {
		return x.Boards
	}
	return nil
}

type ChangeBoardOrderRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Id            int64                               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderToChange *ChangeBoardOrderRequest_BoardOrder `protobuf:"bytes,2,opt,name=order_to_change,json=orderToChange,proto3" json:"order_to_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeBoardOrderRequest) Reset() {
	*x = ChangeBoardOrderRequest{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBoardOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBoardOrderRequest) ProtoMessage() {}

func (x *ChangeBoardOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBoardOrderRequest.ProtoReflect.Descriptor instead.
func (*ChangeBoardOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeBoardOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeBoardOrderRequest) GetOrderToChange() *ChangeBoardOrderRequest_BoardOrder {
	if x != nil {
		return x.OrderToChange
	}
	return nil
}

type ChangeBoardOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeBoardOrderResponse) Reset() {
	*x = ChangeBoardOrderResponse{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBoardOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBoardOrderResponse) ProtoMessage() {}

func (x *ChangeBoardOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBoardOrderResponse.ProtoReflect.Descriptor instead.
func (*ChangeBoardOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{13}
}

type GetBoardsOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardsOrderRequest) Reset() {
	*x = GetBoardsOrderRequest{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardsOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardsOrderRequest) ProtoMessage() {}

func (x *GetBoardsOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardsOrderRequest.ProtoReflect.Descriptor instead.
func (*GetBoardsOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{14}
}

type GetBoardsOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         map[int64]int32        `protobuf:"bytes,1,rep,name=order,proto3" json:"order,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardsOrderResponse) Reset() {
	*x = GetBoardsOrderResponse{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardsOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardsOrderResponse) ProtoMessage() {}

func (x *GetBoardsOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardsOrderResponse.ProtoReflect.Descriptor instead.
func (*GetBoardsOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{15}
}

func (x *GetBoardsOrderResponse) GetOrder() map[int64]int32 {
	if x != nil {
		return x.Order
	}
	return nil
}

type CreateBoardRequest_BoardPrototype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TopicIds      []int64                `protobuf:"varint,2,rep,packed,name=topic_ids,json=topicIds,proto3" json:"topic_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest_BoardPrototype) Reset() {
	*x = CreateBoardRequest_BoardPrototype{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest_BoardPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest_BoardPrototype) ProtoMessage() {}

func (x *CreateBoardRequest_BoardPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest_BoardPrototype.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest_BoardPrototype) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateBoardRequest_BoardPrototype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBoardRequest_BoardPrototype) GetTopicIds() []int64 {
	if x != nil {
		return x.TopicIds
	}
	return nil
}

type UpdateBoardRequest_BoardPrototype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	TopicIds      []int64                `protobuf:"varint,2,rep,packed,name=topic_ids,json=topicIds,proto3" json:"topic_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardRequest_BoardPrototype) Reset() {
	*x = UpdateBoardRequest_BoardPrototype{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardRequest_BoardPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardRequest_BoardPrototype) ProtoMessage() {}

func (x *UpdateBoardRequest_BoardPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardRequest_BoardPrototype.ProtoReflect.Descriptor instead.
func (*UpdateBoardRequest_BoardPrototype) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateBoardRequest_BoardPrototype) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateBoardRequest_BoardPrototype) GetTopicIds() []int64 {
	if x != nil {
		return x.TopicIds
	}
	return nil
}

type ChangeBoardOrderRequest_BoardOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Place         int32                  `protobuf:"varint,1,opt,name=place,proto3" json:"place,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeBoardOrderRequest_BoardOrder) Reset() {
	*x = ChangeBoardOrderRequest_BoardOrder{}
	mi := &file_api_gateway_boards_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBoardOrderRequest_BoardOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBoardOrderRequest_BoardOrder) ProtoMessage() {}

func (x *ChangeBoardOrderRequest_BoardOrder) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_boards_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBoardOrderRequest_BoardOrder.ProtoReflect.Descriptor instead.
func (*ChangeBoardOrderRequest_BoardOrder) Descriptor() ([]byte, []int) {
	return file_api_gateway_boards_services_proto_rawDescGZIP(), []int{12, 0}
}

func (x *ChangeBoardOrderRequest_BoardOrder) GetPlace() int32 {
	if x != nil {
		return x.Place
	}
	return 0
}

var File_api_gateway_boards_services_proto protoreflect.FileDescriptor

const file_api_gateway_boards_services_proto_rawDesc = "" +
	"\n" +
	"!api/gateway/boards/services.proto\x12\x15api.v1.gateway.boards\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fapi/gateway/boards/models.proto\x1a\x1eapi/gateway/tasks/models.proto\x1a\x1fapi/gateway/topics/models.proto\"!\n" +
	"\x0fGetBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"F\n" +
	"\x10GetBoardResponse\x122\n" +
	"\x05board\x18\x01 \x01(\v2\x1c.api.v1.gateway.boards.BoardR\x05board\"\xb9\x01\n" +
	"\x12CreateBoardRequest\x12`\n" +
	"\x0fboard_to_create\x18\x01 \x01(\v28.api.v1.gateway.boards.CreateBoardRequest.BoardPrototypeR\rboardToCreate\x1aA\n" +
	"\x0eBoardPrototype\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttopic_ids\x18\x02 \x03(\x03R\btopicIds\"%\n" +
	"\x13CreateBoardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd7\x01\n" +
	"\x12UpdateBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12`\n" +
	"\x0fboard_to_update\x18\x02 \x01(\v28.api.v1.gateway.boards.UpdateBoardRequest.BoardPrototypeR\rboardToUpdate\x1aO\n" +
	"\x0eBoardPrototype\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\ttopic_ids\x18\x02 \x03(\x03R\btopicIdsB\a\n" +
	"\x05_name\"\x15\n" +
	"\x13UpdateBoardResponse\"$\n" +
	"\x12DeleteBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13DeleteBoardResponse\"(\n" +
	"\x16GetBoardContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"_\n" +
	"\x17GetBoardContentResponse\x12D\n" +
	"\x06topics\x18\x01 \x03(\v2,.api.v1.gateway.topics.TopicWithFetchedTasksR\x06topics\"\x15\n" +
	"\x13GetAllBoardsRequest\"L\n" +
	"\x14GetAllBoardsResponse\x124\n" +
	"\x06boards\x18\x01 \x03(\v2\x1c.api.v1.gateway.boards.BoardR\x06boards\"\xb0\x01\n" +
	"\x17ChangeBoardOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12a\n" +
	"\x0forder_to_change\x18\x02 \x01(\v29.api.v1.gateway.boards.ChangeBoardOrderRequest.BoardOrderR\rorderToChange\x1a\"\n" +
	"\n" +
	"BoardOrder\x12\x14\n" +
	"\x05place\x18\x01 \x01(\x05R\x05place\"\x1a\n" +
	"\x18ChangeBoardOrderResponse\"\x17\n" +
	"\x15GetBoardsOrderRequest\"\xa2\x01\n" +
	"\x16GetBoardsOrderResponse\x12N\n" +
	"\x05order\x18\x01 \x03(\v28.api.v1.gateway.boards.GetBoardsOrderResponse.OrderEntryR\x05order\x1a8\n" +
	"\n" +
	"OrderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\xfd\b\n" +
	"\fBoardService\x12z\n" +
	"\bGetBoard\x12&.api.v1.gateway.boards.GetBoardRequest\x1a'.api.v1.gateway.boards.GetBoardResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/boards/{id=*}\x12\x7f\n" +
	"\vCreateBoard\x12).api.v1.gateway.boards.CreateBoardRequest\x1a*.api.v1.gateway.boards.CreateBoardResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/boards\x12\x94\x01\n" +
	"\vUpdateBoard\x12).api.v1.gateway.boards.UpdateBoardRequest\x1a*.api.v1.gateway.boards.UpdateBoardResponse\".\x82\xd3\xe4\x93\x02(:\x0fboard_to_update2\x15/api/v1/boards/{id=*}\x12\x83\x01\n" +
	"\vDeleteBoard\x12).api.v1.gateway.boards.DeleteBoardRequest\x1a*.api.v1.gateway.boards.DeleteBoardResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/boards/{id=*}\x12\x97\x01\n" +
	"\x0fGetBoardContent\x12-.api.v1.gateway.boards.GetBoardContentRequest\x1a..api.v1.gateway.boards.GetBoardContentResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/boards/{id=*}/content\x12\x7f\n" +
	"\fGetAllBoards\x12*.api.v1.gateway.boards.GetAllBoardsRequest\x1a+.api.v1.gateway.boards.GetAllBoardsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/boards\x12\x8b\x01\n" +
	"\x0eGetBoardsOrder\x12,.api.v1.gateway.boards.GetBoardsOrderRequest\x1a-.api.v1.gateway.boards.GetBoardsOrderResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/boards/order\x12\xa9\x01\n" +
	"\x10ChangeBoardOrder\x12..api.v1.gateway.boards.ChangeBoardOrderRequest\x1a/.api.v1.gateway.boards.ChangeBoardOrderResponse\"4\x82\xd3\xe4\x93\x02.:\x0forder_to_change2\x1b/api/v1/boards/{id=*}/orderBQZOgithub.com/bogi-lyceya-44/gateway/internal/pb/api/gateway/boards;gateway_boardsb\x06proto3"

var (
	file_api_gateway_boards_services_proto_rawDescOnce sync.Once
	file_api_gateway_boards_services_proto_rawDescData []byte
)

func file_api_gateway_boards_services_proto_rawDescGZIP() []byte {
	file_api_gateway_boards_services_proto_rawDescOnce.Do(func() {
		file_api_gateway_boards_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_boards_services_proto_rawDesc), len(file_api_gateway_boards_services_proto_rawDesc)))
	})
	return file_api_gateway_boards_services_proto_rawDescData
}

var file_api_gateway_boards_services_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_gateway_boards_services_proto_goTypes = []any{
	(*GetBoardRequest)(nil),                    // 0: api.v1.gateway.boards.GetBoardRequest
	(*GetBoardResponse)(nil),                   // 1: api.v1.gateway.boards.GetBoardResponse
	(*CreateBoardRequest)(nil),                 // 2: api.v1.gateway.boards.CreateBoardRequest
	(*CreateBoardResponse)(nil),                // 3: api.v1.gateway.boards.CreateBoardResponse
	(*UpdateBoardRequest)(nil),                 // 4: api.v1.gateway.boards.UpdateBoardRequest
	(*UpdateBoardResponse)(nil),                // 5: api.v1.gateway.boards.UpdateBoardResponse
	(*DeleteBoardRequest)(nil),                 // 6: api.v1.gateway.boards.DeleteBoardRequest
	(*DeleteBoardResponse)(nil),                // 7: api.v1.gateway.boards.DeleteBoardResponse
	(*GetBoardContentRequest)(nil),             // 8: api.v1.gateway.boards.GetBoardContentRequest
	(*GetBoardContentResponse)(nil),            // 9: api.v1.gateway.boards.GetBoardContentResponse
	(*GetAllBoardsRequest)(nil),                // 10: api.v1.gateway.boards.GetAllBoardsRequest
	(*GetAllBoardsResponse)(nil),               // 11: api.v1.gateway.boards.GetAllBoardsResponse
	(*ChangeBoardOrderRequest)(nil),            // 12: api.v1.gateway.boards.ChangeBoardOrderRequest
	(*ChangeBoardOrderResponse)(nil),           // 13: api.v1.gateway.boards.ChangeBoardOrderResponse
	(*GetBoardsOrderRequest)(nil),              // 14: api.v1.gateway.boards.GetBoardsOrderRequest
	(*GetBoardsOrderResponse)(nil),             // 15: api.v1.gateway.boards.GetBoardsOrderResponse
	(*CreateBoardRequest_BoardPrototype)(nil),  // 16: api.v1.gateway.boards.CreateBoardRequest.BoardPrototype
	(*UpdateBoardRequest_BoardPrototype)(nil),  // 17: api.v1.gateway.boards.UpdateBoardRequest.BoardPrototype
	(*ChangeBoardOrderRequest_BoardOrder)(nil), // 18: api.v1.gateway.boards.ChangeBoardOrderRequest.BoardOrder
	nil,                                  // 19: api.v1.gateway.boards.GetBoardsOrderResponse.OrderEntry
	(*Board)(nil),                        // 20: api.v1.gateway.boards.Board
	(*topics.TopicWithFetchedTasks)(nil), // 21: api.v1.gateway.topics.TopicWithFetchedTasks
}
var file_api_gateway_boards_services_proto_depIdxs = []int32{
	20, // 0: api.v1.gateway.boards.GetBoardResponse.board:type_name -> api.v1.gateway.boards.Board
	16, // 1: api.v1.gateway.boards.CreateBoardRequest.board_to_create:type_name -> api.v1.gateway.boards.CreateBoardRequest.BoardPrototype
	17, // 2: api.v1.gateway.boards.UpdateBoardRequest.board_to_update:type_name -> api.v1.gateway.boards.UpdateBoardRequest.BoardPrototype
	21, // 3: api.v1.gateway.boards.GetBoardContentResponse.topics:type_name -> api.v1.gateway.topics.TopicWithFetchedTasks
	20, // 4: api.v1.gateway.boards.GetAllBoardsResponse.boards:type_name -> api.v1.gateway.boards.Board
	18, // 5: api.v1.gateway.boards.ChangeBoardOrderRequest.order_to_change:type_name -> api.v1.gateway.boards.ChangeBoardOrderRequest.BoardOrder
	19, // 6: api.v1.gateway.boards.GetBoardsOrderResponse.order:type_name -> api.v1.gateway.boards.GetBoardsOrderResponse.OrderEntry
	0,  // 7: api.v1.gateway.boards.BoardService.GetBoard:input_type -> api.v1.gateway.boards.GetBoardRequest
	2,  // 8: api.v1.gateway.boards.BoardService.CreateBoard:input_type -> api.v1.gateway.boards.CreateBoardRequest
	4,  // 9: api.v1.gateway.boards.BoardService.UpdateBoard:input_type -> api.v1.gateway.boards.UpdateBoardRequest
	6,  // 10: api.v1.gateway.boards.BoardService.DeleteBoard:input_type -> api.v1.gateway.boards.DeleteBoardRequest
	8,  // 11: api.v1.gateway.boards.BoardService.GetBoardContent:input_type -> api.v1.gateway.boards.GetBoardContentRequest
	10, // 12: api.v1.gateway.boards.BoardService.GetAllBoards:input_type -> api.v1.gateway.boards.GetAllBoardsRequest
	14, // 13: api.v1.gateway.boards.BoardService.GetBoardsOrder:input_type -> api.v1.gateway.boards.GetBoardsOrderRequest
	12, // 14: api.v1.gateway.boards.BoardService.ChangeBoardOrder:input_type -> api.v1.gateway.boards.ChangeBoardOrderRequest
	1,  // 15: api.v1.gateway.boards.BoardService.GetBoard:output_type -> api.v1.gateway.boards.GetBoardResponse
	3,  // 16: api.v1.gateway.boards.BoardService.CreateBoard:output_type -> api.v1.gateway.boards.CreateBoardResponse
	5,  // 17: api.v1.gateway.boards.BoardService.UpdateBoard:output_type -> api.v1.gateway.boards.UpdateBoardResponse
	7,  // 18: api.v1.gateway.boards.BoardService.DeleteBoard:output_type -> api.v1.gateway.boards.DeleteBoardResponse
	9,  // 19: api.v1.gateway.boards.BoardService.GetBoardContent:output_type -> api.v1.gateway.boards.GetBoardContentResponse
	11, // 20: api.v1.gateway.boards.BoardService.GetAllBoards:output_type -> api.v1.gateway.boards.GetAllBoardsResponse
	15, // 21: api.v1.gateway.boards.BoardService.GetBoardsOrder:output_type -> api.v1.gateway.boards.GetBoardsOrderResponse
	13, // 22: api.v1.gateway.boards.BoardService.ChangeBoardOrder:output_type -> api.v1.gateway.boards.ChangeBoardOrderResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_gateway_boards_services_proto_init() }
func file_api_gateway_boards_services_proto_init() {
	if File_api_gateway_boards_services_proto != nil {
		return
	}
	file_api_gateway_boards_models_proto_init()
	file_api_gateway_boards_services_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_boards_services_proto_rawDesc), len(file_api_gateway_boards_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_boards_services_proto_goTypes,
		DependencyIndexes: file_api_gateway_boards_services_proto_depIdxs,
		MessageInfos:      file_api_gateway_boards_services_proto_msgTypes,
	}.Build()
	File_api_gateway_boards_services_proto = out.File
	file_api_gateway_boards_services_proto_goTypes = nil
	file_api_gateway_boards_services_proto_depIdxs = nil
}
